language: cpp
dist: focal

compiler:
  - gcc
  - clang

before_script:

  - mkdir build
  - cd build
  - cmake .. -DCODE_COVERAGE=ON

script: make && make test

after_success:
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"