name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install lcov

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: |
          cd build
          cmake .. -DCODE_COVERAGE=ON -DEXAMPLES=OFF

      - name: Build and test
        run: |
          cd build
          make
          make test
        shell: bash

      - name: Collect code coverage
        run: |
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.info
          fail_ci_if_error: false

      - name: Upload code coverage to GitHub
        uses: actions/upload-artifact@v4
        with:
            name: coverage
            path: coverage.info